### ISSUE TITLE
[BUG] Backend is not found in director (during test) 

### ISSUE THREAD

**Issue by mgreenw** [ysugimoto/falco#196]
Hi! Thanks for making such a useful tool.

**Describe the problem**
I am seeing an error when running `falco test -r` where something is going wrong with a backend / director related to shielding. When I run `falco test -r`, I get

```
 Failed to run test: [RuntimeException] backend 'F_Custom_backend' is not found inRemote.Director:ssl_shield_region_state_us at line: 3, position: 4
```

When I run `falco lint`, I see a notice related to this:

```
 2|director ssl_shield_region_state_us random {
   ^^^^^^^^
 3|    { .backend = F_Custom_backend; .weight = 1; }
```

**However**, if I look at the generated VCL directly in fastly, I see this, seemingly missing the backend:

```
director ssl_shield_region_state_us shield {
   .shield = "INTER-REGION-SSL";
}
```

**VCL code that cause the problem**
It seems to be that the code is coming from the fastly remote and not from the local vcl code being linted / tested.

**Expected behavior**
I expect shielding / backends to work for linting and testing.

**Desktop (please complete the following information):**
 - OS: macOS 13.3
 - Shell: zsh

**Comment by ysugimoto** [comment]
Hi @mgreenw , thanks for reaching out to us!

This issue looks interesting and it is caused by Origin-Shielding related configuration.

To explain what occurs:

1. On fetching and generating remote snippets, we will add the first backend declaration into `.backend` property to avoid raising an error (see: https://github.com/ysugimoto/falco/blob/main/snippets/fetch.go#L172)
2. In this case, the director looks to have a special type of "shield" (unfortunately it isn't documented in Fastly)
 
So you could see the falco's error such as having a backend and we assume we could fix this problem by ignoring shield director.

We will do that in a few days, thanks again for reporting that issue that we were not aware of!

**Comment by ysugimoto** [comment]
Hmm, I could not reproduce it.

I've created a service that has an origin with origin-shielding, Faslty shows VCL the following:

```vcl
backend F_Host_1 {
    .between_bytes_timeout = 10s;
    .connect_timeout = 1s;
    .dynamic = true;
    .first_byte_timeout = 15s;
    .host = "example.com";
    .max_connections = 200;
    .port = "443";
    .share_key = "qRK2E1vLIVkQ3BU0iVk9X7";
    .ssl = true;
    .ssl_cert_hostname = "example.com";
    .ssl_check_cert = always;
    .ssl_sni_hostname = "example.com";
    .probe = {
        .dummy = true;
        .initial = 5;
        .request = "HEAD / HTTP/1.1"  "Host: example.com" "Connection: close";
        .threshold = 1;
        .timeout = 2s;
        .window = 5;
      }
}
director ssl_shield_tyo_tokyo_jp shield {
   .shield = "TYO11900-SSL";
}

...
```

Even though some tests are passed without error that you issued. Could you check the `F_Custom_backend` origin is exactly defined (it might not have `F_` prefix)? or sharing your VCLs helps find the problem.

**Comment by mgreenw** [comment]
@ysugimoto Thanks for such a quick response! Yes, that VCL you shared with the backend and the director shield is exactly what I see in our generated VCL. I have confirmed that the backend origin is defined in fastly itself (not in our VCL code), and has the output like you have above.

I'm not able to share the exact VCL, but I will try to come up with a minimal reproduction. Do you think #197 might fix it?

**Comment by ysugimoto** [comment]
@mgreenw It might not be fixed yet because it only adds a director type of `shield` for linting.

I think setting shield director will run in the extracted `#FASTLY RECV` macro, actually Fastly generated VCL has:

```vcl
#--FASTLY RECV BEGIN
  if (req.restarts == 0) {
    if (!req.http.X-Timer) {
      set req.http.X-Timer = "S" time.start.sec "." time.start.usec_frac;
    }
    set req.http.X-Timer = req.http.X-Timer ",VS0";
  }
  declare local var.fastly_req_do_shield BOOL;
  set var.fastly_req_do_shield = (req.restarts == 0);
  # default conditions
  set req.backend = F_Host_1;
    # end default conditions
      #do shield here F_Host_1 > ssl_shield_tyo_tokyo_jp;
  {
    if (req.backend == F_Host_1 && var.fastly_req_do_shield) {
      if (server.datacenter != "TYO" && req.http.Fastly-FF !~ "-TYO") {
        set req.backend = ssl_shield_tyo_tokyo_jp;
      }
      if (!req.backend.healthy) {
        # the shield POP seems unhealthy, so fetch from origin
        set req.backend = F_Host_1;
      }
    }
  }
#--FASTLY RECV END
```

But falco does not extract properly this macro because we don't know what VCL will be generated inside macro by Fastly.

Back to the testing - I'm guessing that your VCL has a `set` statement  that sets shield director as `req.backend` in `vcl_recv` obviously like:

```vcl
sub vcl_recv {
  ...
  set req.backend = ssl_shield_region_state_us; // Do you have this statement?
  ...
}
```

And we documented [here](https://github.com/ysugimoto/falco/blob/develop/docs/simulator.md#simulator-limitations) that Origin-Shielding is unsupported in testing due to our simulator reason but I'm still wondering why `F_Custom_origin` is not defined in the testing. We'd like to solve this problem so I'm pleased that you continue to discuss about 🙂

**Comment by MasonM** [comment]
I encountered this too, and https://github.com/ysugimoto/falco/pull/208 fixes it for me. My fork has binaries with the fix if you want to check: https://github.com/MasonM/falco/releases

**Comment by ysugimoto** [comment]
@mgreenw This issue will be fixed on `v.1.2.0` - Thanks @MasonM a lot!
